"""initial cubrid schema

Revision ID: 1c444a5c4819
Revises:
Create Date: 2026-09-14 11:23:50.240178

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from cii_platform.db.migration_guard import guard_irreversible_downgrade
from cii_platform.db.types import JSONText

# revision identifiers, used by Alembic.
revision: str = "1c444a5c4819"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_app_user"),
    )
    op.create_index("idx_app_user_email", "app_user", ["email"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("user_id", sa.String(length=100), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("details_json", JSONText(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_audit_log"),
    )
    op.create_index(
        "idx_audit_action",
        "audit_log",
        ["action", sa.literal_column('"timestamp" DESC')],
        unique=False,
    )
    op.create_index("idx_audit_entity", "audit_log", ["entity_type", "entity_id"], unique=False)
    op.create_index(
        "idx_audit_timestamp", "audit_log", [sa.literal_column('"timestamp" DESC')], unique=False
    )
    op.create_table(
        "cii_rating_boundary",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ship_type", sa.String(length=50), nullable=False),
        sa.Column("condition_expr", sa.String(length=200), nullable=False),
        sa.Column("capacity_basis", sa.String(length=10), nullable=False),
        sa.Column("d1", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("d2", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("d3", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("d4", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("d1 < d2 AND d2 < d3 AND d3 < d4", name="chk_d_order"),
        sa.PrimaryKeyConstraint("id", name="pk_cii_rating_boundary"),
    )
    op.create_index(
        "idx_boundary_unique", "cii_rating_boundary", ["ship_type", "condition_expr"], unique=True
    )
    op.create_table(
        "cii_reference_line",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ship_type", sa.String(length=50), nullable=False),
        sa.Column("condition_expr", sa.String(length=200), nullable=False),
        sa.Column("capacity_rule", sa.String(length=50), nullable=False),
        sa.Column("a_raw", sa.String(length=50), nullable=False),
        sa.Column("a_decimal", sa.Numeric(precision=30, scale=6), nullable=False),
        sa.Column("c", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "capacity_rule IN ('DWT','GT') OR capacity_rule LIKE 'fixed %'",
            name="chk_capacity_rule",
        ),
        sa.CheckConstraint("a_decimal > 0", name="chk_a_decimal_positive"),
        sa.CheckConstraint("c >= 0", name="chk_c_positive"),
        sa.PrimaryKeyConstraint("id", name="pk_cii_reference_line"),
    )
    op.create_index("idx_refline_ship_type", "cii_reference_line", ["ship_type"], unique=False)
    op.create_index(
        "idx_refline_unique", "cii_reference_line", ["ship_type", "condition_expr"], unique=True
    )
    op.create_table(
        "fuel_type",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("cf", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column(
            "unit", sa.String(length=30), server_default=sa.text("'tCO₂/tFuel'"), nullable=False
        ),
        sa.Column("source_ref", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=50), server_default=sa.text("'1.0'"), nullable=False),
        sa.Column("content_hash", sa.String(length=71), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("cf > 0", name="chk_cf_positive"),
        sa.PrimaryKeyConstraint("id", name="pk_fuel_type"),
        sa.UniqueConstraint("code", name="uq_fuel_type_code"),
    )
    op.create_table(
        "port_geocode",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("query", sa.String(length=200), nullable=False),
        sa.Column("raw_query", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("lon", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_port_geocode"),
        sa.UniqueConstraint("query", name="uq_port_geocode_query"),
    )
    op.create_table(
        "regulation_year",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("z_factor_percent", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("z_factor_percent >= 0", name="chk_z_factor_nonneg"),
        sa.PrimaryKeyConstraint("id", name="pk_regulation_year"),
        sa.UniqueConstraint("year", name="uq_regulation_year_year"),
    )
    op.create_table(
        "simulation_parameter",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile", sa.String(length=30), nullable=False),
        sa.Column("variable", sa.String(length=20), nullable=False),
        sa.Column("distribution", sa.String(length=20), nullable=False),
        sa.Column("bound_type", sa.String(length=10), nullable=False),
        sa.Column("min_value", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("mode_value", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("max_value", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("floor_value", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("source_ref", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("bound_type IN ('FACTOR','DELTA')", name="chk_sim_param_bound_type"),
        sa.CheckConstraint("distribution IN ('TRIANGULAR')", name="chk_sim_param_distribution"),
        sa.CheckConstraint(
            "\"variable\" IN ('DISTANCE','FUEL','SPEED')", name="chk_sim_param_variable"
        ),
        sa.CheckConstraint(
            "floor_value IS NULL OR floor_value > 0", name="chk_sim_param_floor_positive"
        ),
        sa.CheckConstraint(
            "min_value <= mode_value AND mode_value <= max_value",
            name="chk_sim_param_bounds_ordered",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_simulation_parameter"),
    )
    op.create_index(
        "idx_sim_param_unique", "simulation_parameter", ["profile", "variable"], unique=True
    )
    op.create_table(
        "vessel",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("imo_number", sa.String(length=7), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("ship_type", sa.String(length=50), nullable=False),
        sa.Column("gross_tonnage", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("deadweight", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("default_fuel_type", sa.String(length=30), nullable=True),
        sa.Column("reference_speed_kn", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("reference_daily_foc_ton", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column(
            "is_cii_applicable_hint", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("underway_state", sa.String(length=20), nullable=True),
        sa.Column("detail_status", sa.String(length=20), nullable=True),
        sa.Column("current_lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("current_lon", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("position_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(underway_state IS NULL AND detail_status IS NULL) OR (underway_state IS NOT NULL "
            "AND detail_status IS NOT NULL AND (underway_state = 'UNDER_WAY' AND detail_status = "
            "'SAILING' OR underway_state = 'NOT_UNDER_WAY' AND detail_status IN "
            "('IN_PORT','AT_ANCHOR','DRIFTING','STS','CANAL_TRANSIT','DRYDOCK')))",
            name="chk_vessel_state_pair",
        ),
        sa.CheckConstraint(
            "detail_status IS NULL OR detail_status IN "
            "('SAILING','IN_PORT','AT_ANCHOR','DRIFTING','STS','CANAL_TRANSIT','DRYDOCK')",
            name="chk_detail_status_allowed",
        ),
        sa.CheckConstraint(
            "underway_state IS NULL OR underway_state IN ('UNDER_WAY','NOT_UNDER_WAY')",
            name="chk_underway_state_allowed",
        ),
        sa.CheckConstraint(
            "(current_lat IS NULL AND current_lon IS NULL) OR (current_lat IS NOT NULL AND "
            "current_lon IS NOT NULL AND position_updated_at IS NOT NULL)",
            name="chk_vessel_position_pair",
        ),
        sa.CheckConstraint(
            "current_lat IS NULL OR current_lat BETWEEN -90 AND 90", name="chk_vessel_lat_range"
        ),
        sa.CheckConstraint(
            "current_lon IS NULL OR current_lon BETWEEN -180 AND 180", name="chk_vessel_lon_range"
        ),
        sa.CheckConstraint("deadweight IS NULL OR deadweight > 0", name="chk_dwt_positive"),
        sa.CheckConstraint(
            "reference_speed_kn IS NULL OR reference_speed_kn > 0", name="chk_speed_positive"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_vessel"),
    )
    op.create_index("idx_vessel_imo", "vessel", ["imo_number"], unique=True)
    op.create_index("idx_vessel_name", "vessel", ["name"], unique=False)
    op.create_index("idx_vessel_ship_type", "vessel", ["ship_type"], unique=False)
    op.create_table(
        "weather_model_parameter",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=True),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_weather_model_parameter"),
    )
    op.create_index(
        "idx_weather_param_unique", "weather_model_parameter", ["model_version", "key"], unique=True
    )
    op.create_table(
        "weather_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("lon", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("lat_rounded", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("lon_rounded", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("wave_height_m", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("wave_direction_deg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("wave_period_s", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("wind_speed_ms", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("wind_direction_deg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_weather_snapshot"),
    )
    op.create_index(
        "idx_weather_cache",
        "weather_snapshot",
        ["lat_rounded", "lon_rounded", sa.literal_column("fetched_at DESC")],
        unique=False,
    )
    op.create_table(
        "chat_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("expires_at > created_at", name="chk_chat_session_expires"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name="fk_chat_session_user", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_chat_session"),
    )
    op.create_index("idx_chat_session_expires", "chat_session", ["expires_at"], unique=False)
    op.create_index(
        "idx_chat_session_user",
        "chat_session",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "simulation_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vessel_id", sa.Uuid(), nullable=False),
        sa.Column("regulation_year", sa.Integer(), nullable=False),
        sa.Column("voyages_json", JSONText(), nullable=False),
        sa.Column("vessel_json", JSONText(), nullable=True),
        sa.Column("input_hash", sa.String(length=71), nullable=False),
        sa.Column("parameter_hash", sa.String(length=71), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"], ["vessel.id"], name="fk_simulation_snapshot_vessel", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_simulation_snapshot"),
    )
    op.create_index(
        "idx_snapshot_vessel",
        "simulation_snapshot",
        ["vessel_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "user_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name="fk_user_session_user", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_user_session"),
    )
    op.create_index("idx_session_expiry", "user_session", ["expires_at"], unique=False)
    op.create_index("idx_session_token", "user_session", ["session_token_hash"], unique=True)
    op.create_index(
        "idx_session_user",
        "user_session",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "user_token",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('EMAIL_VERIFY', 'PASSWORD_RESET')", name="chk_user_token_purpose"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name="fk_user_token_user", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_user_token"),
    )
    op.create_index("idx_user_token_hash", "user_token", ["token_hash"], unique=True)
    op.create_index(
        "idx_user_token_user_purpose", "user_token", ["user_id", "purpose"], unique=False
    )
    op.create_table(
        "vessel_position_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vessel_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("lon", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("sog_kn", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("cog_deg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("nav_status", sa.SmallInteger(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\"source\" IN ('MANUAL','AIS','SIMULATED')", name="chk_vessel_position_snapshot_source"
        ),
        sa.CheckConstraint(
            "cog_deg IS NULL OR (cog_deg >= 0 AND cog_deg < 360)",
            name="chk_vessel_position_snapshot_cog",
        ),
        sa.CheckConstraint("lat BETWEEN -90 AND 90", name="chk_vessel_position_snapshot_lat"),
        sa.CheckConstraint("lon BETWEEN -180 AND 180", name="chk_vessel_position_snapshot_lon"),
        sa.CheckConstraint(
            "nav_status IS NULL OR (nav_status >= 0 AND nav_status <= 15)",
            name="chk_vessel_position_snapshot_nav_status",
        ),
        sa.CheckConstraint(
            "sog_kn IS NULL OR sog_kn >= 0", name="chk_vessel_position_snapshot_sog"
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"],
            ["vessel.id"],
            name="fk_vessel_position_snapshot_vessel",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_vessel_position_snapshot"),
    )
    op.create_index(
        "idx_vessel_position_snapshot_vessel_observed",
        "vessel_position_snapshot",
        ["vessel_id", sa.literal_column("observed_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_vessel_position_snapshot_observation",
        "vessel_position_snapshot",
        ["vessel_id", "source", "observed_at"],
        unique=True,
    )
    op.create_table(
        "voyage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vessel_id", sa.Uuid(), nullable=False),
        sa.Column("voyage_no", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("regulation_year", sa.Integer(), nullable=True),
        sa.Column("departure_port_name", sa.String(length=200), nullable=False),
        sa.Column("departure_lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("departure_lon", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("arrival_port_name", sa.String(length=200), nullable=False),
        sa.Column("arrival_lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("arrival_lon", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("planned_distance_nm", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("actual_distance_nm", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("planned_speed_kn", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("actual_avg_speed_kn", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("planned_departure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_arrival_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_departure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_arrival_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "annual_inclusion_policy",
            sa.String(length=30),
            server_default=sa.text("'EXCLUDE'"),
            nullable=False,
        ),
        sa.Column(
            "created_from", sa.String(length=30), server_default=sa.text("'MANUAL'"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "annual_inclusion_policy = 'EXCLUDE' OR regulation_year IS NOT NULL",
            name="chk_year_policy",
        ),
        sa.CheckConstraint(
            "annual_inclusion_policy IN ('EXCLUDE','INCLUDE_AS_PLAN','INCLUDE_AS_ACTUAL')",
            name="chk_voyage_policy",
        ),
        sa.CheckConstraint(
            '"status" IN '
            "('DRAFT','PLANNED','IN_PROGRESS','COMPLETED','CONFIRMED','CANCELLED','ARCHIVED')",
            name="chk_voyage_status",
        ),
        sa.CheckConstraint(
            "(\"status\" = 'DRAFT' AND annual_inclusion_policy = 'EXCLUDE') OR (\"status\" IN "
            "('PLANNED','IN_PROGRESS') AND annual_inclusion_policy IN "
            "('EXCLUDE','INCLUDE_AS_PLAN')) OR (\"status\" IN ('COMPLETED','CONFIRMED') AND "
            "annual_inclusion_policy IN ('EXCLUDE','INCLUDE_AS_ACTUAL')) OR (\"status\" IN "
            "('CANCELLED','ARCHIVED') AND annual_inclusion_policy = 'EXCLUDE')",
            name="chk_status_policy",
        ),
        sa.CheckConstraint(
            "actual_avg_speed_kn IS NULL OR actual_avg_speed_kn >= 1.0",
            name="chk_actual_speed_positive",
        ),
        sa.CheckConstraint(
            "actual_distance_nm IS NULL OR actual_distance_nm > 0", name="chk_actual_dist_positive"
        ),
        sa.CheckConstraint(
            "arrival_lat IS NULL OR arrival_lat BETWEEN -90 AND 90", name="chk_arr_lat_range"
        ),
        sa.CheckConstraint(
            "arrival_lon IS NULL OR arrival_lon BETWEEN -180 AND 180", name="chk_arr_lon_range"
        ),
        sa.CheckConstraint(
            "departure_lat IS NULL OR departure_lat BETWEEN -90 AND 90", name="chk_dep_lat_range"
        ),
        sa.CheckConstraint(
            "departure_lon IS NULL OR departure_lon BETWEEN -180 AND 180", name="chk_dep_lon_range"
        ),
        sa.CheckConstraint("planned_distance_nm > 0", name="chk_distance_positive"),
        sa.CheckConstraint("planned_speed_kn >= 1.0", name="chk_speed_positive"),
        sa.CheckConstraint(
            "regulation_year IS NULL OR regulation_year BETWEEN 2019 AND 2050",
            name="chk_regulation_year_range",
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"], ["vessel.id"], name="fk_voyage_vessel", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_voyage"),
    )
    op.create_index("idx_voyage_status", "voyage", ["vessel_id", "status"], unique=False)
    op.create_index(
        "idx_voyage_vessel",
        "voyage",
        ["vessel_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("idx_voyage_year", "voyage", ["vessel_id", "regulation_year"], unique=False)
    op.create_table(
        "calculation_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("calculation_type", sa.String(length=30), nullable=False),
        sa.Column("vessel_id", sa.Uuid(), nullable=False),
        sa.Column("voyage_id", sa.Uuid(), nullable=True),
        sa.Column("weather_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("input_hash", sa.String(length=71), nullable=False),
        sa.Column("parameter_hash", sa.String(length=71), nullable=False),
        sa.Column("model_version", JSONText(), nullable=False),
        sa.Column("result_json", JSONText(), nullable=False),
        sa.Column("parameters_used", JSONText(), nullable=False),
        sa.Column("warnings_json", JSONText(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("needs_recalc", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "calculation_type IN "
            "('VOYAGE_ESTIMATE','SCENARIO','ANNUAL_DETERMINISTIC','ANNUAL_MONTE_CARLO')",
            name="chk_calculation_type",
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"], ["vessel.id"], name="fk_calculation_run_vessel", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["voyage_id"], ["voyage.id"], name="fk_calculation_run_voyage", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["weather_snapshot_id"],
            ["weather_snapshot.id"],
            name="fk_calculation_run_weather_snapshot",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_calculation_run"),
    )
    op.create_index(
        "idx_calc_input_hash", "calculation_run", ["input_hash", "parameter_hash"], unique=False
    )
    op.create_index(
        "idx_calc_type",
        "calculation_run",
        ["calculation_type", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_calc_vessel",
        "calculation_run",
        ["vessel_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_calc_weather_snapshot", "calculation_run", ["weather_snapshot_id"], unique=False
    )
    op.create_table(
        "chat_message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "sent_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("\"role\" IN ('USER','ASSISTANT')", name="chk_chat_message_role"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["chat_session.id"], name="fk_chat_message_session", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_chat_message"),
    )
    op.create_index(
        "idx_chat_message_session", "chat_message", ["session_id", "sent_at"], unique=False
    )
    op.create_table(
        "not_underway_period",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vessel_id", sa.Uuid(), nullable=False),
        sa.Column("regulation_year", sa.Integer(), nullable=False),
        sa.Column("period_type", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("port_name", sa.String(length=200), nullable=True),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lon", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("voyage_id", sa.Uuid(), nullable=True),
        sa.Column(
            "distance_nm",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "period_type IN ('IN_PORT','AT_ANCHOR','DRIFTING','STS','CANAL_TRANSIT','DRYDOCK')",
            name="chk_not_underway_period_type",
        ),
        sa.CheckConstraint("distance_nm >= 0", name="chk_nup_distance_non_negative"),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at > started_at", name="chk_not_underway_period_time_order"
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"], ["vessel.id"], name="fk_not_underway_period_vessel", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["voyage_id"], ["voyage.id"], name="fk_not_underway_period_voyage", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_not_underway_period"),
    )
    op.create_index(
        "idx_not_underway_period_vessel_started",
        "not_underway_period",
        ["vessel_id", "started_at"],
        unique=False,
    )
    op.create_index(
        "idx_not_underway_period_vessel_year",
        "not_underway_period",
        ["vessel_id", "regulation_year"],
        unique=False,
    )
    op.create_index(
        "idx_not_underway_period_voyage", "not_underway_period", ["voyage_id"], unique=False
    )
    op.create_table(
        "voyage_fuel_use",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("voyage_id", sa.Uuid(), nullable=False),
        sa.Column("fuel_type", sa.String(length=30), nullable=False),
        sa.Column("planned_fuel_ton", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("actual_fuel_ton", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("cf_used", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\"source\" IN ('USER_INPUT','MODEL_ESTIMATE','IMPORT','SAMPLE')",
            name="chk_fuel_source",
        ),
        sa.CheckConstraint(
            "actual_fuel_ton IS NULL OR actual_fuel_ton > 0", name="chk_actual_fuel_positive"
        ),
        sa.CheckConstraint(
            "planned_fuel_ton IS NULL OR planned_fuel_ton > 0", name="chk_fuel_positive"
        ),
        sa.ForeignKeyConstraint(
            ["voyage_id"], ["voyage.id"], name="fk_voyage_fuel_use_voyage", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_voyage_fuel_use"),
    )
    op.create_index(
        "idx_fuel_use_unique", "voyage_fuel_use", ["voyage_id", "fuel_type"], unique=True
    )
    op.create_table(
        "voyage_scenario",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vessel_id", sa.Uuid(), nullable=False),
        sa.Column("voyage_id", sa.Uuid(), nullable=True),
        sa.Column("scenario_type", sa.String(length=20), nullable=False),
        sa.Column("scenario_name", sa.String(length=100), nullable=False),
        sa.Column("distance_nm", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("speed_kn", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("duration_hours", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("fuel_ton", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("weather_factor", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("cii_value", sa.Numeric(precision=15, scale=8), nullable=False),
        sa.Column("estimated_rating", sa.String(length=1), nullable=False),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("is_adopted", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("weather_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("estimated_rating IN ('A','B','C','D','E')", name="chk_scenario_rating"),
        sa.CheckConstraint(
            "risk_level IN ('LOW','MEDIUM','HIGH','CRITICAL')", name="chk_scenario_risk"
        ),
        sa.CheckConstraint(
            "scenario_type IN ('DIRECT','DETOUR','SLOW_STEAMING')", name="chk_scenario_type"
        ),
        sa.CheckConstraint("distance_nm > 0", name="chk_scenario_distance_positive"),
        sa.CheckConstraint("duration_hours > 0", name="chk_scenario_duration_positive"),
        sa.CheckConstraint("fuel_ton > 0", name="chk_scenario_fuel_positive"),
        sa.CheckConstraint("speed_kn >= 1.0", name="chk_scenario_speed_positive"),
        sa.ForeignKeyConstraint(
            ["vessel_id"], ["vessel.id"], name="fk_voyage_scenario_vessel", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["voyage_id"], ["voyage.id"], name="fk_voyage_scenario_voyage", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["weather_snapshot_id"],
            ["weather_snapshot.id"],
            name="fk_voyage_scenario_weather",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_voyage_scenario"),
    )
    op.create_index(
        "idx_scenario_vessel",
        "voyage_scenario",
        ["vessel_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("idx_scenario_voyage", "voyage_scenario", ["voyage_id"], unique=False)
    op.create_table(
        "annual_simulation_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("calculation_run_id", sa.Uuid(), nullable=False),
        sa.Column("vessel_id", sa.Uuid(), nullable=False),
        sa.Column("regulation_year", sa.Integer(), nullable=False),
        sa.Column("target_rating", sa.String(length=1), nullable=False),
        sa.Column("simulation_runs", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column(
            "apply_feedback_factor", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("target_rating IN ('A','B','C','D')", name="chk_target_rating"),
        sa.CheckConstraint("simulation_runs > 0", name="chk_sim_runs_positive"),
        sa.ForeignKeyConstraint(
            ["calculation_run_id"],
            ["calculation_run.id"],
            name="fk_annual_simulation_run_calculation_run",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["simulation_snapshot.id"],
            name="fk_annual_simulation_run_snapshot",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"],
            ["vessel.id"],
            name="fk_annual_simulation_run_vessel",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_annual_simulation_run"),
        # ⚠️ `DB_SCHEMA §2.6 [S-6]`의 1:1 보장이 **DB에서 강제되지 않는다** (`#1058`).
        #
        # 종전 PostgreSQL 스키마는 `CREATE UNIQUE INDEX idx_sim_snapshot_unique ON
        # annual_simulation_run (snapshot_id)`로 「1스냅샷 = 1시뮬레이션」을 못 박았다.
        # CUBRID 전환 과정에서 그 줄이 **사유 없이 주석으로 꺼져** 있었고, 되살리려
        # 시도한 결과 CUBRID에서는 어느 형태로도 서지 않는 것을 확인했다.
        #
        #   CREATE UNIQUE INDEX …        → Index "fk_annual_simulation_run_snapshot"
        #   sa.UniqueConstraint(…)          already defined for class
        #                                   "dba.annual_simulation_run" (errno=-272)
        #
        # CUBRID는 FK에 인덱스를 자동으로 만들고, 같은 컬럼에 인덱스를 또 두는 것을
        # 거부한다. 지금 상태에서는 **한 스냅샷에 연간 시뮬레이션이 여러 건 매달릴 수
        # 있다.** 어떻게 할지(FK를 빼고 UNIQUE를 남길지 · 앱 계층에서 막을지 · 정본을
        # 고칠지)는 정본 규칙이 걸린 결정이라 여기서 임의로 정하지 않았다.
    )
    op.create_table(
        "not_underway_fuel_use",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("period_id", sa.Uuid(), nullable=False),
        sa.Column("consumer_type", sa.String(length=20), nullable=False),
        sa.Column("fuel_type", sa.String(length=30), nullable=False),
        sa.Column("fuel_ton", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cf_used", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.CheckConstraint(
            "consumer_type IN ('MAIN_ENGINE','AUX_ENGINE','OIL_FIRED_BOILER','OTHER')",
            name="chk_not_underway_consumer_type",
        ),
        sa.CheckConstraint("cf_used > 0", name="chk_nufu_cf_used_positive"),
        sa.CheckConstraint("fuel_ton > 0", name="chk_not_underway_fuel_positive"),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["not_underway_period.id"],
            name="fk_not_underway_fuel_use_period",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_not_underway_fuel_use"),
    )
    op.create_index(
        "idx_not_underway_fuel_use_unique",
        "not_underway_fuel_use",
        ["period_id", "consumer_type", "fuel_type"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """스키마 전체를 드롭한다 — 프로덕션에서는 막는다 (#819 · DB_SCHEMA §8.1.2).

    되돌림의 단위가 스키마 전체다. 종전에는 리비전 하나만 내릴 수 있었지만, 이
    initial 하나로 합쳐진 뒤로는 **전부이거나 아무것도 아니다.**
    """
    # 무엇이든 지우기 전에 끊는다 — 가드는 downgrade() 맨 앞에 선다.
    guard_irreversible_downgrade("1c444a5c4819")
    # CUBRID는 `DROP INDEX <이름>`을 받지 않는다 — `... ON <테이블>`을 요구한다.
    # 개별 인덱스를 지우지 않고 **테이블만 드롭한다**. 테이블을 드롭하면 그 인덱스도
    # 함께 사라지므로 결과가 같고, 방언별 문법 차이를 타지 않는다 (`#1058`).
    op.drop_table("not_underway_fuel_use")
    op.drop_table("annual_simulation_run")
    op.drop_table("voyage_scenario")
    op.drop_table("voyage_fuel_use")
    op.drop_table("not_underway_period")
    op.drop_table("chat_message")
    op.drop_table("calculation_run")
    op.drop_table("voyage")
    op.drop_table("vessel_position_snapshot")
    op.drop_table("user_token")
    op.drop_table("user_session")
    op.drop_table("simulation_snapshot")
    op.drop_table("chat_session")
    op.drop_table("weather_snapshot")
    op.drop_table("weather_model_parameter")
    op.drop_table("vessel")
    op.drop_table("simulation_parameter")
    op.drop_table("regulation_year")
    op.drop_table("port_geocode")
    op.drop_table("fuel_type")
    op.drop_table("cii_reference_line")
    op.drop_table("cii_rating_boundary")
    op.drop_table("audit_log")
    op.drop_table("app_user")
    # ### end Alembic commands ###
